---
label: Portfolio
hide_body: false
fields:
- type: text
  name: company
  label: Company
- name: company_logo
  label: Logo
  type: file
  description: Dimensions work best at 400 pixels by 100 pixels
  hidden: false
  default: ''
- name: website_url
  type: text
  label: Website URL
  description: Link to company website
- name: order
  type: number
  label: Order
  description: The order they should show up on the site
  default: 0
pages:
- _portfolio/Coloursmith Labs.md
- _portfolio/Bluefield Seeding Solutions.md
- _portfolio/Stash.md
- _portfolio/Island Water Technologies.md
- _portfolio/Garago.md
- _portfolio/Forestry.md
