---
label: Portfolio
hide_body: false
fields:
- type: text
  name: company
  label: Company
- name: company_logo
  label: Logo
  type: file
  description: Dimensions work best at 400 pixels by 100 pixels
  hidden: false
  default: ''
